title: Saaraa Kazi
url: "https://saphiraa.github.io/DeveloperPortfolio/"
baseurl: "/DeveloperPortfolio"

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://github.com/Saphiraa"
footer_text: "Saaraa Kazi | FullStack Software Developer"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/DeveloperPortfolio/"
 - name: "Resume"
   link: "SAARAA KAZI RESUME - Projects.pdf"
 - name: "Contact"
   link: "/DeveloperPortfolio/contact"

name: Developer Portfolio
